package app;

public class stationReportObj {
    int location;
    String DMY;
    int precipitation;
    String precipQual;
    int rainDaysNum;
    int rainDaysMeasure;
    double evaporation;
    String evapQual;
    int evapDaysNum;
    double maxTemp;
    String maxTempQual;
    int maxTempDays;
    double minTemp;
    String minTempQual;
    int minTempDays;
    int humid00;
    String humid00Qual;
    int humid03;
    String humid03Qual;
    int humid06;
    String humid06Qual;
    int humid09;
    String humid09Qual;
    int humid12;
    String humid12Qual;
    int humid15;
    String humid15Qual;
    int humid18;
    String humid18Qual;
    int humid21;
    String humid21Qual;
    double sunshine;
    String sunshineQual;
    int okta00;
    String okta00Qual;
    int okta03;
    String okta03Qual;
    int okta06;
    String okta06Qual;
    int okta09;
    String okta09Qual;
    int okta12;
    String okta12Qual;
    int okta15;
    String okta15Qual;
    int okta18;
    String okta18Qual;
    int okta21;
    String okta21Qual;

    public stationReportObj(int location, String DMY, int precipitation, String precipQual, int rainDaysNum, int rainDaysMeasure, double evaporation, String evapQual, int evapDaysNum, double maxTemp, String maxTempQual, int maxTempDays, double minTemp, String minTempQual, int minTempDays, int humid00, String humid00Qual, int humid03, String humid03Qual, int humid06, String humid06Qual, int humid09, String humid09Qual, int humid12, String humid12Qual, int humid15, String humid15Qual, int humid18, String humid18Qual, int humid21, String humid21Qual, double sunshine, String sunshineQual, int okta00, String okta00Qual, int okta03, String okta03Qual, int okta06, String okta06Qual, int okta09, String okta09Qual, int okta12, String okta12Qual, int okta15, String okta15Qual, int okta18, String okta18Qual, int okta21, String okta21Qual) {
        this.location = location;
        this.DMY = DMY;
        this.precipitation = precipitation;
        this.precipQual = precipQual;
        this.rainDaysNum = rainDaysNum;
        this.rainDaysMeasure = rainDaysMeasure;
        this.evaporation = evaporation;
        this.evapQual = evapQual;
        this.evapDaysNum = evapDaysNum;
        this.maxTemp = maxTemp;
        this.maxTempQual = maxTempQual;
        this.maxTempDays = maxTempDays;
        this.minTemp = minTemp;
        this.minTempQual = minTempQual;
        this.minTempDays = minTempDays;
        this.humid00 = humid00;
        this.humid00Qual = humid00Qual;
        this.humid03 = humid03;
        this.humid03Qual = humid03Qual;
        this.humid06 = humid06;
        this.humid06Qual = humid06Qual;
        this.humid09 = humid09;
        this.humid09Qual = humid09Qual;
        this.humid12 = humid12;
        this.humid12Qual = humid12Qual;
        this.humid15 = humid15;
        this.humid15Qual = humid15Qual;
        this.humid18 = humid18;
        this.humid18Qual = humid18Qual;
        this.humid21 = humid21;
        this.humid21Qual = humid21Qual;
        this.sunshine = sunshine;
        this.sunshineQual = sunshineQual;
        this.okta00 = okta00;
        this.okta00Qual = okta00Qual;
        this.okta03 = okta03;
        this.okta03Qual = okta03Qual;
        this.okta06 = okta06;
        this.okta06Qual = okta06Qual;
        this.okta09 = okta09;
        this.okta09Qual = okta09Qual;
        this.okta12 = okta12;
        this.okta12Qual = okta12Qual;
        this.okta15 = okta15;
        this.okta15Qual = okta15Qual;
        this.okta18 = okta18;
        this.okta18Qual = okta18Qual;
        this.okta21 = okta21;
        this.okta21Qual = okta21Qual;
    }

    public stationReportObj() {
        this.location = 0;
        this.DMY = "";
        this.precipitation = 0;
        this.precipQual = "";
        this.rainDaysNum = 0;
        this.rainDaysMeasure = 0;
        this.evaporation = 0.0;
        this.evapQual = "";
        this.evapDaysNum = 0;
        this.maxTemp = 0.0;
        this.maxTempQual = "";
        this.maxTempDays = 0;
        this.minTemp = 0.0;
        this.minTempQual = "";
        this.minTempDays = 0;
        this.humid00 = 0;
        this.humid00Qual = "";
        this.humid03 = 0;
        this.humid03Qual = "";
        this.humid06 = 0;
        this.humid06Qual = "";
        this.humid09 = 0;
        this.humid09Qual = "";
        this.humid12 = 0;
        this.humid12Qual = "";
        this.humid15 = 0;
        this.humid15Qual = "";
        this.humid18 = 0;
        this.humid18Qual = "";
        this.humid21 = 0;
        this.humid21Qual = "";
        this.sunshine = 0.0;
        this.sunshineQual = "";
        this.okta00 = 0;
        this.okta00Qual = "";
        this.okta03 = 0;
        this.okta03Qual = "";
        this.okta06 = 0;
        this.okta06Qual = "";
        this.okta09 = 0;
        this.okta09Qual = "";
        this.okta12 = 0;
        this.okta12Qual = "";
        this.okta15 = 0;
        this.okta15Qual = "";
        this.okta18 = 0;
        this.okta18Qual = "";
        this.okta21 = 0;
        this.okta21Qual = "";
    }
    
}
